// Generated by CoffeeScript 1.6.3
var app;

app = angular.module('focusOn', []);

app.directive('focusOn', function() {
  return function(scope, elem, attr) {
    if(attr.focusOn){
      return scope.$on('focusOn', function(e, name) {
        if (name === attr.focusOn) {
          return elem[0].focus();
        }
      });
    }
  };
});

app.factory('focus', [
  '$rootScope', '$timeout', (function($rootScope, $timeout) {
    return function(name) {
      var _ref;
      if ((_ref = navigator.platform) === 'iPod' || _ref === 'iPhone' || _ref === 'iPad') {
        return $rootScope.$broadcast('focusOn', name);
      } else {
        return $timeout(function() {
          return $rootScope.$broadcast('focusOn', name);
        });
      }
    };
  })
]);
